### ISSUE TITLE
creditcard.php

### ISSUE THREAD

**Issue by Tigrap** [aponkral/whmcs-tckimlik#4]
Merhaba eklenti için teşekkürler ancak aşamadığım bir sorun var. Eklenti aktifken creditcard.php sayfasından ödeme alamıyorum. Tckn ve doğum tarihi girilmedi hatası veriyor, ancak üye profilinde bu bilgiler kayıtlı ve ilgili müşteri alanları eklentide seçili. Kayıt sırasında eklenti sorunsuz çalışıyor 

sadece creditcard.php sayfasında kart bilgilerini girip ödeme yapmak isteyen kullanıcı sorun yaşıyor ve kullanıcının karşısına bu bilgileri girebileceği özel müşteri alanları dahi çıkmıyor bu sayfada.

Bu sorunu nasıl aşabilirim

**Comment by aponkralnet** [comment]
Merhaba @Tigrap 

Sipariş formunda veya ödeme formunda kimlik bilgileri alanı bulunmuyor olabilir. İlgili özel müşteri alanları için "sepette göster"i aktif ettiniz mi?

**Comment by Tigrap** [comment]
Merhaba,

'sipariş formunda göster' şeklinde geçiyor ve evet aktif
dediğim gibi kayıt olunurken bir sorun yok ama creditcard.php de sorun çıkartıyor

**Comment by aponkralnet** [comment]
İlgili kredi kartı sayfasında T.C Kimlik Numarası ve Doğum Yılı alanı mevcut mu?22.07.2020, 17:33, "Tigrap" <notifications@github.com>:
Merhaba,
'sipariş formunda göster' şeklinde geçiyor ve evet aktif
dediğim gibi kayıt olunurken bir sorun yok ama creditcard.php de sorun çıkartıyor

**Comment by Tigrap** [comment]
hayır mevcut değil ama dediğim gibi profilde kayıtlı

**Comment by aponkralnet** [comment]
İlgili alanın olması gerekmektedir. Temanızı kontrol ettirebilirsiniz.

**Comment by Tigrap** [comment]
Orjinal whmcs six temasında da çıkmıyor yalnız

**Comment by aponkralnet** [comment]
Daha detaylı kontrol için ekran görüntüleri ile destekler misiniz?

**Comment by Tigrap** [comment]
http://vds.ist/tckn/Screenshot_88.png
http://vds.ist/tckn/Screenshot_89.png
http://vds.ist/tckn/Screenshot_90.png
http://vds.ist/tckn/Screenshot_91.png

**Comment by aponkralnet** [comment]
İlgili formda gerekli alanların ikisi de mevcut değildir.Modüle şu şekilde düzeltme uygulanabilir:- Eğer bir formdaki gerekli veri gönderilmemişse veritabanından kontrol edilsinŞimdilik güncelleme gelene kadar bu sorunu yaşamaya devam edeceksiniz. Yakın zamanda yeni bir düzeltme güncellemesi geliştirmeyi planlamıyoruz.Saygılarımızla,Abdullah,Aponkral

**Comment by Tigrap** [comment]
https://prnt.sc/tpi033

hooks.php de creditcard.php neden var onu çözemedim. Bunu kaldırınca modül hiç çalışmıyor...

**Comment by aponkralnet** [comment]
Modülde aslında sorun yok. Sadece sizin kullandığınız ödeme modülü ile uyumlu değil. Bir çok firma Aponkral'ın geliştirdiği WHMCS T.C. Kimlik Doğrulama modülünü kullanmaktadır.
